// Reference DXCC entity list, parsed from country-files.com's cty.dat (the
// community-maintained entity/prefix database most ham radio logging software
// uses -- same numbering as the ARRL's own DXCC list). Used only for the
// Most-Wanted DXCC feature: the full universe of possible entities to diff
// worked entities against. Not guaranteed to perfectly track ARRL's current
// vs. deleted entity status -- treat as a general reference, not authoritative.
export type DxccEntity = { name: string; cqZone: number; continent: string };

export const DXCC_ENTITIES: DxccEntity[] = [
  { name: 'Afghanistan', cqZone: 21, continent: 'AS' },
  { name: 'African Italy', cqZone: 33, continent: 'AF' },
  { name: 'Agalega & St. Brandon', cqZone: 39, continent: 'AF' },
  { name: 'Aland Islands', cqZone: 15, continent: 'EU' },
  { name: 'Alaska', cqZone: 1, continent: 'NA' },
  { name: 'Albania', cqZone: 15, continent: 'EU' },
  { name: 'Algeria', cqZone: 33, continent: 'AF' },
  { name: 'American Samoa', cqZone: 32, continent: 'OC' },
  { name: 'Amsterdam & St. Paul Is.', cqZone: 39, continent: 'AF' },
  { name: 'Andaman & Nicobar Is.', cqZone: 26, continent: 'AS' },
  { name: 'Andorra', cqZone: 14, continent: 'EU' },
  { name: 'Angola', cqZone: 36, continent: 'AF' },
  { name: 'Anguilla', cqZone: 8, continent: 'NA' },
  { name: 'Annobon Island', cqZone: 36, continent: 'AF' },
  { name: 'Antarctica', cqZone: 13, continent: 'SA' },
  { name: 'Antigua & Barbuda', cqZone: 8, continent: 'NA' },
  { name: 'Argentina', cqZone: 13, continent: 'SA' },
  { name: 'Armenia', cqZone: 21, continent: 'AS' },
  { name: 'Aruba', cqZone: 9, continent: 'SA' },
  { name: 'Ascension Island', cqZone: 36, continent: 'AF' },
  { name: 'Asiatic Russia', cqZone: 17, continent: 'AS' },
  { name: 'Asiatic Turkey', cqZone: 20, continent: 'AS' },
  { name: 'Austral Islands', cqZone: 32, continent: 'OC' },
  { name: 'Australia', cqZone: 30, continent: 'OC' },
  { name: 'Austria', cqZone: 15, continent: 'EU' },
  { name: 'Aves Island', cqZone: 8, continent: 'NA' },
  { name: 'Azerbaijan', cqZone: 21, continent: 'AS' },
  { name: 'Azores', cqZone: 14, continent: 'EU' },
  { name: 'Bahamas', cqZone: 8, continent: 'NA' },
  { name: 'Bahrain', cqZone: 21, continent: 'AS' },
  { name: 'Baker & Howland Islands', cqZone: 31, continent: 'OC' },
  { name: 'Balearic Islands', cqZone: 14, continent: 'EU' },
  { name: 'Banaba Island', cqZone: 31, continent: 'OC' },
  { name: 'Bangladesh', cqZone: 22, continent: 'AS' },
  { name: 'Barbados', cqZone: 8, continent: 'NA' },
  { name: 'Bear Island', cqZone: 40, continent: 'EU' },
  { name: 'Belarus', cqZone: 16, continent: 'EU' },
  { name: 'Belgium', cqZone: 14, continent: 'EU' },
  { name: 'Belize', cqZone: 7, continent: 'NA' },
  { name: 'Benin', cqZone: 35, continent: 'AF' },
  { name: 'Bermuda', cqZone: 5, continent: 'NA' },
  { name: 'Bhutan', cqZone: 22, continent: 'AS' },
  { name: 'Bolivia', cqZone: 10, continent: 'SA' },
  { name: 'Bonaire', cqZone: 9, continent: 'SA' },
  { name: 'Bosnia-Herzegovina', cqZone: 15, continent: 'EU' },
  { name: 'Botswana', cqZone: 38, continent: 'AF' },
  { name: 'Bouvet', cqZone: 38, continent: 'AF' },
  { name: 'Brazil', cqZone: 11, continent: 'SA' },
  { name: 'British Virgin Islands', cqZone: 8, continent: 'NA' },
  { name: 'Brunei Darussalam', cqZone: 28, continent: 'OC' },
  { name: 'Bulgaria', cqZone: 20, continent: 'EU' },
  { name: 'Burkina Faso', cqZone: 35, continent: 'AF' },
  { name: 'Burundi', cqZone: 36, continent: 'AF' },
  { name: 'Cambodia', cqZone: 26, continent: 'AS' },
  { name: 'Cameroon', cqZone: 36, continent: 'AF' },
  { name: 'Canada', cqZone: 5, continent: 'NA' },
  { name: 'Canary Islands', cqZone: 33, continent: 'AF' },
  { name: 'Cape Verde', cqZone: 35, continent: 'AF' },
  { name: 'Cayman Islands', cqZone: 8, continent: 'NA' },
  { name: 'Central African Republic', cqZone: 36, continent: 'AF' },
  { name: 'Central Kiribati', cqZone: 31, continent: 'OC' },
  { name: 'Ceuta & Melilla', cqZone: 33, continent: 'AF' },
  { name: 'Chad', cqZone: 36, continent: 'AF' },
  { name: 'Chagos Islands', cqZone: 39, continent: 'AF' },
  { name: 'Chatham Islands', cqZone: 32, continent: 'OC' },
  { name: 'Chesterfield Islands', cqZone: 30, continent: 'OC' },
  { name: 'Chile', cqZone: 12, continent: 'SA' },
  { name: 'China', cqZone: 24, continent: 'AS' },
  { name: 'Christmas Island', cqZone: 29, continent: 'OC' },
  { name: 'Clipperton Island', cqZone: 7, continent: 'NA' },
  { name: 'Cocos (Keeling) Islands', cqZone: 29, continent: 'OC' },
  { name: 'Cocos Island', cqZone: 7, continent: 'NA' },
  { name: 'Colombia', cqZone: 9, continent: 'SA' },
  { name: 'Comoros', cqZone: 39, continent: 'AF' },
  { name: 'Conway Reef', cqZone: 32, continent: 'OC' },
  { name: 'Corsica', cqZone: 15, continent: 'EU' },
  { name: 'Costa Rica', cqZone: 7, continent: 'NA' },
  { name: 'Cote d\'Ivoire', cqZone: 35, continent: 'AF' },
  { name: 'Crete', cqZone: 20, continent: 'EU' },
  { name: 'Croatia', cqZone: 15, continent: 'EU' },
  { name: 'Crozet Island', cqZone: 39, continent: 'AF' },
  { name: 'Cuba', cqZone: 8, continent: 'NA' },
  { name: 'Curacao', cqZone: 9, continent: 'SA' },
  { name: 'Cyprus', cqZone: 20, continent: 'AS' },
  { name: 'Czech Republic', cqZone: 15, continent: 'EU' },
  { name: 'Dem. Rep. of the Congo', cqZone: 36, continent: 'AF' },
  { name: 'Denmark', cqZone: 14, continent: 'EU' },
  { name: 'Desecheo Island', cqZone: 8, continent: 'NA' },
  { name: 'Djibouti', cqZone: 37, continent: 'AF' },
  { name: 'Dodecanese', cqZone: 20, continent: 'EU' },
  { name: 'Dominica', cqZone: 8, continent: 'NA' },
  { name: 'Dominican Republic', cqZone: 8, continent: 'NA' },
  { name: 'DPR of Korea', cqZone: 25, continent: 'AS' },
  { name: 'Ducie Island', cqZone: 32, continent: 'OC' },
  { name: 'East Malaysia', cqZone: 28, continent: 'OC' },
  { name: 'Easter Island', cqZone: 12, continent: 'SA' },
  { name: 'Eastern Kiribati', cqZone: 31, continent: 'OC' },
  { name: 'Ecuador', cqZone: 10, continent: 'SA' },
  { name: 'Egypt', cqZone: 34, continent: 'AF' },
  { name: 'El Salvador', cqZone: 7, continent: 'NA' },
  { name: 'England', cqZone: 14, continent: 'EU' },
  { name: 'Equatorial Guinea', cqZone: 36, continent: 'AF' },
  { name: 'Eritrea', cqZone: 37, continent: 'AF' },
  { name: 'Estonia', cqZone: 15, continent: 'EU' },
  { name: 'Ethiopia', cqZone: 37, continent: 'AF' },
  { name: 'European Russia', cqZone: 16, continent: 'EU' },
  { name: 'European Turkey', cqZone: 20, continent: 'EU' },
  { name: 'Falkland Islands', cqZone: 13, continent: 'SA' },
  { name: 'Faroe Islands', cqZone: 14, continent: 'EU' },
  { name: 'Fed. Rep. of Germany', cqZone: 14, continent: 'EU' },
  { name: 'Fernando de Noronha', cqZone: 11, continent: 'SA' },
  { name: 'Fiji', cqZone: 32, continent: 'OC' },
  { name: 'Finland', cqZone: 15, continent: 'EU' },
  { name: 'France', cqZone: 14, continent: 'EU' },
  { name: 'Franz Josef Land', cqZone: 40, continent: 'EU' },
  { name: 'French Guiana', cqZone: 9, continent: 'SA' },
  { name: 'French Polynesia', cqZone: 32, continent: 'OC' },
  { name: 'Gabon', cqZone: 36, continent: 'AF' },
  { name: 'Galapagos Islands', cqZone: 10, continent: 'SA' },
  { name: 'Georgia', cqZone: 21, continent: 'AS' },
  { name: 'Ghana', cqZone: 35, continent: 'AF' },
  { name: 'Gibraltar', cqZone: 14, continent: 'EU' },
  { name: 'Glorioso Islands', cqZone: 39, continent: 'AF' },
  { name: 'Greece', cqZone: 20, continent: 'EU' },
  { name: 'Greenland', cqZone: 40, continent: 'NA' },
  { name: 'Grenada', cqZone: 8, continent: 'NA' },
  { name: 'Guadeloupe', cqZone: 8, continent: 'NA' },
  { name: 'Guam', cqZone: 27, continent: 'OC' },
  { name: 'Guantanamo Bay', cqZone: 8, continent: 'NA' },
  { name: 'Guatemala', cqZone: 7, continent: 'NA' },
  { name: 'Guernsey', cqZone: 14, continent: 'EU' },
  { name: 'Guinea', cqZone: 35, continent: 'AF' },
  { name: 'Guinea-Bissau', cqZone: 35, continent: 'AF' },
  { name: 'Guyana', cqZone: 9, continent: 'SA' },
  { name: 'Haiti', cqZone: 8, continent: 'NA' },
  { name: 'Hawaii', cqZone: 31, continent: 'OC' },
  { name: 'Heard Island', cqZone: 39, continent: 'AF' },
  { name: 'Honduras', cqZone: 7, continent: 'NA' },
  { name: 'Hong Kong', cqZone: 24, continent: 'AS' },
  { name: 'Hungary', cqZone: 15, continent: 'EU' },
  { name: 'Iceland', cqZone: 40, continent: 'EU' },
  { name: 'India', cqZone: 22, continent: 'AS' },
  { name: 'Indonesia', cqZone: 28, continent: 'OC' },
  { name: 'Iran', cqZone: 21, continent: 'AS' },
  { name: 'Iraq', cqZone: 21, continent: 'AS' },
  { name: 'Ireland', cqZone: 14, continent: 'EU' },
  { name: 'Isle of Man', cqZone: 14, continent: 'EU' },
  { name: 'Israel', cqZone: 20, continent: 'AS' },
  { name: 'Italy', cqZone: 15, continent: 'EU' },
  { name: 'ITU HQ', cqZone: 14, continent: 'EU' },
  { name: 'Jamaica', cqZone: 8, continent: 'NA' },
  { name: 'Jan Mayen', cqZone: 40, continent: 'EU' },
  { name: 'Japan', cqZone: 25, continent: 'AS' },
  { name: 'Jersey', cqZone: 14, continent: 'EU' },
  { name: 'Johnston Island', cqZone: 31, continent: 'OC' },
  { name: 'Jordan', cqZone: 20, continent: 'AS' },
  { name: 'Juan de Nova, Europa', cqZone: 39, continent: 'AF' },
  { name: 'Juan Fernandez Islands', cqZone: 12, continent: 'SA' },
  { name: 'Kaliningrad', cqZone: 15, continent: 'EU' },
  { name: 'Kazakhstan', cqZone: 17, continent: 'AS' },
  { name: 'Kenya', cqZone: 37, continent: 'AF' },
  { name: 'Kerguelen Islands', cqZone: 39, continent: 'AF' },
  { name: 'Kermadec Islands', cqZone: 32, continent: 'OC' },
  { name: 'Kingdom of Eswatini', cqZone: 38, continent: 'AF' },
  { name: 'Kure Island', cqZone: 31, continent: 'OC' },
  { name: 'Kuwait', cqZone: 21, continent: 'AS' },
  { name: 'Kyrgyzstan', cqZone: 17, continent: 'AS' },
  { name: 'Lakshadweep Islands', cqZone: 22, continent: 'AS' },
  { name: 'Laos', cqZone: 26, continent: 'AS' },
  { name: 'Latvia', cqZone: 15, continent: 'EU' },
  { name: 'Lebanon', cqZone: 20, continent: 'AS' },
  { name: 'Lesotho', cqZone: 38, continent: 'AF' },
  { name: 'Liberia', cqZone: 35, continent: 'AF' },
  { name: 'Libya', cqZone: 34, continent: 'AF' },
  { name: 'Liechtenstein', cqZone: 14, continent: 'EU' },
  { name: 'Lithuania', cqZone: 15, continent: 'EU' },
  { name: 'Lord Howe Island', cqZone: 30, continent: 'OC' },
  { name: 'Luxembourg', cqZone: 14, continent: 'EU' },
  { name: 'Macao', cqZone: 24, continent: 'AS' },
  { name: 'Macquarie Island', cqZone: 30, continent: 'OC' },
  { name: 'Madagascar', cqZone: 39, continent: 'AF' },
  { name: 'Madeira Islands', cqZone: 33, continent: 'AF' },
  { name: 'Malawi', cqZone: 37, continent: 'AF' },
  { name: 'Maldives', cqZone: 22, continent: 'AS' },
  { name: 'Mali', cqZone: 35, continent: 'AF' },
  { name: 'Malpelo Island', cqZone: 9, continent: 'SA' },
  { name: 'Malta', cqZone: 15, continent: 'EU' },
  { name: 'Mariana Islands', cqZone: 27, continent: 'OC' },
  { name: 'Market Reef', cqZone: 15, continent: 'EU' },
  { name: 'Marquesas Islands', cqZone: 31, continent: 'OC' },
  { name: 'Marshall Islands', cqZone: 31, continent: 'OC' },
  { name: 'Martinique', cqZone: 8, continent: 'NA' },
  { name: 'Mauritania', cqZone: 35, continent: 'AF' },
  { name: 'Mauritius', cqZone: 39, continent: 'AF' },
  { name: 'Mayotte', cqZone: 39, continent: 'AF' },
  { name: 'Mellish Reef', cqZone: 30, continent: 'OC' },
  { name: 'Mexico', cqZone: 6, continent: 'NA' },
  { name: 'Micronesia', cqZone: 27, continent: 'OC' },
  { name: 'Midway Island', cqZone: 31, continent: 'OC' },
  { name: 'Minami Torishima', cqZone: 27, continent: 'OC' },
  { name: 'Moldova', cqZone: 16, continent: 'EU' },
  { name: 'Monaco', cqZone: 14, continent: 'EU' },
  { name: 'Mongolia', cqZone: 23, continent: 'AS' },
  { name: 'Montenegro', cqZone: 15, continent: 'EU' },
  { name: 'Montserrat', cqZone: 8, continent: 'NA' },
  { name: 'Morocco', cqZone: 33, continent: 'AF' },
  { name: 'Mount Athos', cqZone: 20, continent: 'EU' },
  { name: 'Mozambique', cqZone: 37, continent: 'AF' },
  { name: 'Myanmar', cqZone: 26, continent: 'AS' },
  { name: 'N.Z. Subantarctic Is.', cqZone: 32, continent: 'OC' },
  { name: 'Namibia', cqZone: 38, continent: 'AF' },
  { name: 'Nauru', cqZone: 31, continent: 'OC' },
  { name: 'Navassa Island', cqZone: 8, continent: 'NA' },
  { name: 'Nepal', cqZone: 22, continent: 'AS' },
  { name: 'Netherlands', cqZone: 14, continent: 'EU' },
  { name: 'New Caledonia', cqZone: 32, continent: 'OC' },
  { name: 'New Zealand', cqZone: 32, continent: 'OC' },
  { name: 'Nicaragua', cqZone: 7, continent: 'NA' },
  { name: 'Niger', cqZone: 35, continent: 'AF' },
  { name: 'Nigeria', cqZone: 35, continent: 'AF' },
  { name: 'Niue', cqZone: 32, continent: 'OC' },
  { name: 'Norfolk Island', cqZone: 32, continent: 'OC' },
  { name: 'North Cook Islands', cqZone: 32, continent: 'OC' },
  { name: 'North Macedonia', cqZone: 15, continent: 'EU' },
  { name: 'Northern Ireland', cqZone: 14, continent: 'EU' },
  { name: 'Norway', cqZone: 14, continent: 'EU' },
  { name: 'Ogasawara', cqZone: 27, continent: 'AS' },
  { name: 'Oman', cqZone: 21, continent: 'AS' },
  { name: 'Pakistan', cqZone: 21, continent: 'AS' },
  { name: 'Palau', cqZone: 27, continent: 'OC' },
  { name: 'Palestine', cqZone: 20, continent: 'AS' },
  { name: 'Palmyra & Jarvis Islands', cqZone: 31, continent: 'OC' },
  { name: 'Panama', cqZone: 7, continent: 'NA' },
  { name: 'Papua New Guinea', cqZone: 28, continent: 'OC' },
  { name: 'Paraguay', cqZone: 11, continent: 'SA' },
  { name: 'Peru', cqZone: 10, continent: 'SA' },
  { name: 'Peter 1 Island', cqZone: 12, continent: 'SA' },
  { name: 'Philippines', cqZone: 27, continent: 'OC' },
  { name: 'Pitcairn Island', cqZone: 32, continent: 'OC' },
  { name: 'Poland', cqZone: 15, continent: 'EU' },
  { name: 'Portugal', cqZone: 14, continent: 'EU' },
  { name: 'Pr. Edward & Marion Is.', cqZone: 38, continent: 'AF' },
  { name: 'Pratas Island', cqZone: 24, continent: 'AS' },
  { name: 'Puerto Rico', cqZone: 8, continent: 'NA' },
  { name: 'Qatar', cqZone: 21, continent: 'AS' },
  { name: 'Republic of Korea', cqZone: 25, continent: 'AS' },
  { name: 'Republic of Kosovo', cqZone: 15, continent: 'EU' },
  { name: 'Republic of South Sudan', cqZone: 34, continent: 'AF' },
  { name: 'Republic of the Congo', cqZone: 36, continent: 'AF' },
  { name: 'Reunion Island', cqZone: 39, continent: 'AF' },
  { name: 'Revillagigedo', cqZone: 6, continent: 'NA' },
  { name: 'Rodriguez Island', cqZone: 39, continent: 'AF' },
  { name: 'Romania', cqZone: 20, continent: 'EU' },
  { name: 'Rotuma Island', cqZone: 32, continent: 'OC' },
  { name: 'Rwanda', cqZone: 36, continent: 'AF' },
  { name: 'Saba & St. Eustatius', cqZone: 8, continent: 'NA' },
  { name: 'Sable Island', cqZone: 5, continent: 'NA' },
  { name: 'Samoa', cqZone: 32, continent: 'OC' },
  { name: 'San Andres & Providencia', cqZone: 7, continent: 'NA' },
  { name: 'San Felix & San Ambrosio', cqZone: 12, continent: 'SA' },
  { name: 'San Marino', cqZone: 15, continent: 'EU' },
  { name: 'Sao Tome & Principe', cqZone: 36, continent: 'AF' },
  { name: 'Sardinia', cqZone: 15, continent: 'EU' },
  { name: 'Saudi Arabia', cqZone: 21, continent: 'AS' },
  { name: 'Scarborough Reef', cqZone: 27, continent: 'AS' },
  { name: 'Scotland', cqZone: 14, continent: 'EU' },
  { name: 'Senegal', cqZone: 35, continent: 'AF' },
  { name: 'Serbia', cqZone: 15, continent: 'EU' },
  { name: 'Seychelles', cqZone: 39, continent: 'AF' },
  { name: 'Shetland Islands', cqZone: 14, continent: 'EU' },
  { name: 'Sicily', cqZone: 15, continent: 'EU' },
  { name: 'Sierra Leone', cqZone: 35, continent: 'AF' },
  { name: 'Singapore', cqZone: 28, continent: 'AS' },
  { name: 'Sint Maarten', cqZone: 8, continent: 'NA' },
  { name: 'Slovak Republic', cqZone: 15, continent: 'EU' },
  { name: 'Slovenia', cqZone: 15, continent: 'EU' },
  { name: 'Solomon Islands', cqZone: 28, continent: 'OC' },
  { name: 'Somalia', cqZone: 37, continent: 'AF' },
  { name: 'South Africa', cqZone: 38, continent: 'AF' },
  { name: 'South Cook Islands', cqZone: 32, continent: 'OC' },
  { name: 'South Georgia Island', cqZone: 13, continent: 'SA' },
  { name: 'South Orkney Islands', cqZone: 13, continent: 'SA' },
  { name: 'South Sandwich Islands', cqZone: 13, continent: 'SA' },
  { name: 'South Shetland Islands', cqZone: 13, continent: 'SA' },
  { name: 'Sov Mil Order of Malta', cqZone: 15, continent: 'EU' },
  { name: 'Spain', cqZone: 14, continent: 'EU' },
  { name: 'Spratly Islands', cqZone: 26, continent: 'AS' },
  { name: 'Sri Lanka', cqZone: 22, continent: 'AS' },
  { name: 'St. Barthelemy', cqZone: 8, continent: 'NA' },
  { name: 'St. Helena', cqZone: 36, continent: 'AF' },
  { name: 'St. Kitts & Nevis', cqZone: 8, continent: 'NA' },
  { name: 'St. Lucia', cqZone: 8, continent: 'NA' },
  { name: 'St. Martin', cqZone: 8, continent: 'NA' },
  { name: 'St. Paul Island', cqZone: 5, continent: 'NA' },
  { name: 'St. Peter & St. Paul', cqZone: 11, continent: 'SA' },
  { name: 'St. Pierre & Miquelon', cqZone: 5, continent: 'NA' },
  { name: 'St. Vincent', cqZone: 8, continent: 'NA' },
  { name: 'Sudan', cqZone: 34, continent: 'AF' },
  { name: 'Suriname', cqZone: 9, continent: 'SA' },
  { name: 'Svalbard', cqZone: 40, continent: 'EU' },
  { name: 'Swains Island', cqZone: 32, continent: 'OC' },
  { name: 'Sweden', cqZone: 14, continent: 'EU' },
  { name: 'Switzerland', cqZone: 14, continent: 'EU' },
  { name: 'Syria', cqZone: 20, continent: 'AS' },
  { name: 'Taiwan', cqZone: 24, continent: 'AS' },
  { name: 'Tajikistan', cqZone: 17, continent: 'AS' },
  { name: 'Tanzania', cqZone: 37, continent: 'AF' },
  { name: 'Temotu Province', cqZone: 32, continent: 'OC' },
  { name: 'Thailand', cqZone: 26, continent: 'AS' },
  { name: 'The Gambia', cqZone: 35, continent: 'AF' },
  { name: 'Timor - Leste', cqZone: 28, continent: 'OC' },
  { name: 'Togo', cqZone: 35, continent: 'AF' },
  { name: 'Tokelau Islands', cqZone: 31, continent: 'OC' },
  { name: 'Tonga', cqZone: 32, continent: 'OC' },
  { name: 'Trindade & Martim Vaz', cqZone: 11, continent: 'SA' },
  { name: 'Trinidad & Tobago', cqZone: 9, continent: 'SA' },
  { name: 'Tristan da Cunha & Gough', cqZone: 38, continent: 'AF' },
  { name: 'Tromelin Island', cqZone: 39, continent: 'AF' },
  { name: 'Tunisia', cqZone: 33, continent: 'AF' },
  { name: 'Turkmenistan', cqZone: 17, continent: 'AS' },
  { name: 'Turks & Caicos Islands', cqZone: 8, continent: 'NA' },
  { name: 'Tuvalu', cqZone: 31, continent: 'OC' },
  { name: 'Uganda', cqZone: 37, continent: 'AF' },
  { name: 'UK Base Areas on Cyprus', cqZone: 20, continent: 'AS' },
  { name: 'Ukraine', cqZone: 16, continent: 'EU' },
  { name: 'United Arab Emirates', cqZone: 21, continent: 'AS' },
  { name: 'United Nations HQ', cqZone: 5, continent: 'NA' },
  { name: 'United States', cqZone: 5, continent: 'NA' },
  { name: 'Uruguay', cqZone: 13, continent: 'SA' },
  { name: 'US Virgin Islands', cqZone: 8, continent: 'NA' },
  { name: 'Uzbekistan', cqZone: 17, continent: 'AS' },
  { name: 'Vanuatu', cqZone: 32, continent: 'OC' },
  { name: 'Vatican City', cqZone: 15, continent: 'EU' },
  { name: 'Venezuela', cqZone: 9, continent: 'SA' },
  { name: 'Vienna Intl Ctr', cqZone: 15, continent: 'EU' },
  { name: 'Vietnam', cqZone: 26, continent: 'AS' },
  { name: 'Wake Island', cqZone: 31, continent: 'OC' },
  { name: 'Wales', cqZone: 14, continent: 'EU' },
  { name: 'Wallis & Futuna Islands', cqZone: 32, continent: 'OC' },
  { name: 'West Malaysia', cqZone: 28, continent: 'AS' },
  { name: 'Western Kiribati', cqZone: 31, continent: 'OC' },
  { name: 'Western Sahara', cqZone: 33, continent: 'AF' },
  { name: 'Willis Island', cqZone: 30, continent: 'OC' },
  { name: 'Yemen', cqZone: 21, continent: 'AS' },
  { name: 'Zambia', cqZone: 36, continent: 'AF' },
  { name: 'Zimbabwe', cqZone: 38, continent: 'AF' },
];

// The log's qsos.country values come from QRZ/LoTW's own ADIF export and
// don't always spell entity names the same way cty.dat does (different
// community-maintained lists, same underlying DXCC numbering). This maps the
// ~40 mismatches found by diffing the two lists to their cty.dat name(s).
// Russia and Turkey are irreducibly ambiguous from country name alone -- QRZ's
// COUNTRY field doesn't distinguish European/Asiatic sub-entities the way
// cty.dat's callsign-prefix rules do, so both are credited as worked rather
// than risking a false "still needed" claim.
export const COUNTRY_ALIASES: Record<string, string[]> = {
  'Agalega and St Brandon': ['Agalega & St. Brandon'],
  'Andaman and Nicobar Islands': ['Andaman & Nicobar Is.'],
  'Antigua and Barbuda': ['Antigua & Barbuda'],
  'Bosnia and Herzegovina': ['Bosnia-Herzegovina'],
  'Bouvet Island': ['Bouvet'],
  'Brunei': ['Brunei Darussalam'],
  'Ceuta and Melilla': ['Ceuta & Melilla'],
  'Cocos-Keeling Islands': ['Cocos (Keeling) Islands'],
  'Congo': ['Republic of the Congo'],
  'Cyprus SBA': ['UK Base Areas on Cyprus'],
  'East Kiribati': ['Eastern Kiribati'],
  'Eswatini': ['Kingdom of Eswatini'],
  'Germany': ['Fed. Rep. of Germany'],
  'Kiribati': ['Western Kiribati'],
  'Madeira Island': ['Madeira Islands'],
  'North Macedonia (Republic of)': ['North Macedonia'],
  'Palmyra, Jarvis Island': ['Palmyra & Jarvis Islands'],
  'Reunion': ['Reunion Island'],
  'Russia': ['European Russia', 'Asiatic Russia'],
  'SMO Malta': ['Sov Mil Order of Malta'],
  'Saba, St Eustatius': ['Saba & St. Eustatius'],
  'San Andres and Providencia': ['San Andres & Providencia'],
  'South Korea': ['Republic of Korea'],
  'South Sudan': ['Republic of South Sudan'],
  'St Helena Island': ['St. Helena'],
  'St Kitts and Nevis': ['St. Kitts & Nevis'],
  'St Lucia': ['St. Lucia'],
  'St Martin': ['St. Martin'],
  'St Paul Island': ['St. Paul Island'],
  'St Pierre & Miquelon': ['St. Pierre & Miquelon'],
  'St Vincent': ['St. Vincent'],
  'St. Maarten': ['Sint Maarten'],
  'Timor Leste': ['Timor - Leste'],
  'Trindade and Martim Vaz Island': ['Trindade & Martim Vaz'],
  'Trinidad and Tobago': ['Trinidad & Tobago'],
  'Turkey': ['Asiatic Turkey', 'European Turkey'],
  'Turks and  Caicos Islands': ['Turks & Caicos Islands'],
  'Vatican': ['Vatican City'],
  'Wallis and Futuna Islands': ['Wallis & Futuna Islands'],
  // Not a real DXCC entity -- a QRZ marker for maritime-mobile/invalid contacts.
  'NON-DXCC': [],
};

/** Resolves a set of qsos.country strings to their canonical cty.dat entity names. */
export function resolveWorkedEntities(countries: string[]): Set<string> {
  const ctyNames = new Set(DXCC_ENTITIES.map((e) => e.name));
  const resolved = new Set<string>();
  for (const country of countries) {
    if (ctyNames.has(country)) {
      resolved.add(country);
      continue;
    }
    const aliases = COUNTRY_ALIASES[country];
    if (aliases) {
      for (const a of aliases) resolved.add(a);
    }
  }
  return resolved;
}
